# Лабораторная №2
16.	Выполнить обработку элементов прямоугольной матрицы A, имеющей N строк и M столбцов. Исключить из матрицы строку с номером L. Сомкнуть строки матрицы.

In [44]:
import numpy as np

print("Import N rows :");
N = int(input());
print("Import M collumns :");
M = int(input());
print("Import row L to remove :"); 
L = int(input());

arr = np.array(range(0,N*M)).reshape((N,M));
arr = np.delete(arr, L, axis = 1);

print(arr);
print(arr.flatten())

Import N rows :


 5


Import M collumns :


 5


Import row L to remove :


 2


[[ 0  1  3  4]
 [ 5  6  8  9]
 [10 11 13 14]
 [15 16 18 19]
 [20 21 23 24]]
[ 0  1  3  4  5  6  8  9 10 11 13 14 15 16 18 19 20 21 23 24]
